"""Core data models used throughout the trading system."""

from __future__ import annotations

import time
import uuid
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Optional


class Side(str, Enum):
    BUY = "BUY"
    SELL = "SELL"


class OrderType(str, Enum):
    MARKET = "MARKET"
    LIMIT = "LIMIT"
    STOP = "STOP"


class OrderStatus(str, Enum):
    PENDING = "PENDING"
    SUBMITTED = "SUBMITTED"
    FILLED = "FILLED"
    PARTIALLY_FILLED = "PARTIALLY_FILLED"
    CANCELLED = "CANCELLED"
    REJECTED = "REJECTED"


class PositionStatus(str, Enum):
    OPEN = "OPEN"
    CLOSED = "CLOSED"


class SignalStrength(str, Enum):
    WEAK = "WEAK"
    MODERATE = "MODERATE"
    STRONG = "STRONG"


@dataclass
class Tick:
    """Real-time price tick from broker."""
    instrument: str
    bid: float
    ask: float
    spread: float  # in pips
    timestamp: datetime

    @property
    def mid(self) -> float:
        return (self.bid + self.ask) / 2.0


@dataclass
class Candle:
    """OHLCV candle data."""
    instrument: str
    timeframe: str  # e.g., "M1", "M5", "H1", "D"
    timestamp: datetime
    open: float
    high: float
    low: float
    close: float
    volume: int
    complete: bool  # True if candle is closed


@dataclass
class Signal:
    """Trading signal generated by a strategy."""
    id: str = field(default_factory=lambda: str(uuid.uuid4())[:8])
    strategy: str = ""
    instrument: str = ""
    side: Side = Side.BUY
    strength: SignalStrength = SignalStrength.MODERATE
    entry_price: float = 0.0
    stop_loss: float = 0.0
    take_profit: float = 0.0
    risk_reward_ratio: float = 0.0
    reason: str = ""
    metadata: dict = field(default_factory=dict)
    timestamp: datetime = field(default_factory=datetime.utcnow)

    def __post_init__(self):
        if self.entry_price and self.stop_loss and self.take_profit:
            risk = abs(self.entry_price - self.stop_loss)
            reward = abs(self.take_profit - self.entry_price)
            self.risk_reward_ratio = reward / risk if risk > 0 else 0.0


@dataclass
class Order:
    """Order to be submitted to the broker."""
    id: str = field(default_factory=lambda: str(uuid.uuid4())[:8])
    signal_id: str = ""
    instrument: str = ""
    side: Side = Side.BUY
    order_type: OrderType = OrderType.LIMIT
    units: float = 0.0  # position size in units (not lots)
    price: Optional[float] = None  # for limit orders
    stop_loss: float = 0.0
    take_profit: float = 0.0
    status: OrderStatus = OrderStatus.PENDING
    broker_order_id: Optional[str] = None
    strategy: str = ""
    fill_price: Optional[float] = None
    fill_time: Optional[datetime] = None
    created_at: datetime = field(default_factory=datetime.utcnow)


@dataclass
class Position:
    """An open or closed trading position."""
    id: str = field(default_factory=lambda: str(uuid.uuid4())[:8])
    instrument: str = ""
    side: Side = Side.BUY
    units: float = 0.0
    entry_price: float = 0.0
    stop_loss: float = 0.0
    take_profit: float = 0.0
    current_price: float = 0.0
    unrealized_pnl: float = 0.0
    realized_pnl: float = 0.0
    status: PositionStatus = PositionStatus.OPEN
    strategy: str = ""
    broker_trade_id: Optional[str] = None
    opened_at: datetime = field(default_factory=datetime.utcnow)
    closed_at: Optional[datetime] = None
    close_reason: str = ""  # "stop_loss", "take_profit", "manual", "kill_switch"

    @property
    def risk_amount(self) -> float:
        """Dollar risk from entry to stop loss."""
        if not self.stop_loss:
            return 0.0
        return abs(self.entry_price - self.stop_loss) * abs(self.units)


@dataclass
class AccountState:
    """Current account snapshot."""
    balance: float = 0.0
    equity: float = 0.0  # balance + unrealized P&L
    margin_used: float = 0.0
    margin_available: float = 0.0
    unrealized_pnl: float = 0.0
    open_position_count: int = 0
    peak_equity: float = 0.0
    daily_pnl: float = 0.0
    timestamp: datetime = field(default_factory=datetime.utcnow)

    @property
    def drawdown_pct(self) -> float:
        """Current drawdown from peak equity as percentage."""
        if self.peak_equity <= 0:
            return 0.0
        return ((self.peak_equity - self.equity) / self.peak_equity) * 100.0


# Instrument metadata for forex pairs — 24/5 coverage across all sessions
FOREX_PAIRS = {
    # === MAJORS (7) — tightest spreads, highest liquidity ===
    "EUR_USD": {"pip_size": 0.0001, "pip_value_per_unit": 0.0001, "min_units": 1, "avg_spread_pips": 1.2, "sessions": ["london", "newyork"]},
    "GBP_USD": {"pip_size": 0.0001, "pip_value_per_unit": 0.0001, "min_units": 1, "avg_spread_pips": 1.5, "sessions": ["london", "newyork"]},
    "USD_JPY": {"pip_size": 0.01, "pip_value_per_unit": 0.01, "min_units": 1, "avg_spread_pips": 1.0, "sessions": ["tokyo", "newyork"]},
    "USD_CHF": {"pip_size": 0.0001, "pip_value_per_unit": 0.0001, "min_units": 1, "avg_spread_pips": 1.6, "sessions": ["london", "newyork"]},
    "AUD_USD": {"pip_size": 0.0001, "pip_value_per_unit": 0.0001, "min_units": 1, "avg_spread_pips": 1.4, "sessions": ["tokyo", "newyork"]},
    "USD_CAD": {"pip_size": 0.0001, "pip_value_per_unit": 0.0001, "min_units": 1, "avg_spread_pips": 1.8, "sessions": ["newyork"]},
    "NZD_USD": {"pip_size": 0.0001, "pip_value_per_unit": 0.0001, "min_units": 1, "avg_spread_pips": 2.0, "sessions": ["tokyo"]},

    # === JPY CROSSES — best during Tokyo session ===
    "EUR_JPY": {"pip_size": 0.01, "pip_value_per_unit": 0.01, "min_units": 1, "avg_spread_pips": 1.5, "sessions": ["tokyo", "london"]},
    "GBP_JPY": {"pip_size": 0.01, "pip_value_per_unit": 0.01, "min_units": 1, "avg_spread_pips": 2.5, "sessions": ["tokyo", "london"]},
    "AUD_JPY": {"pip_size": 0.01, "pip_value_per_unit": 0.01, "min_units": 1, "avg_spread_pips": 2.0, "sessions": ["tokyo"]},
    "CAD_JPY": {"pip_size": 0.01, "pip_value_per_unit": 0.01, "min_units": 1, "avg_spread_pips": 2.2, "sessions": ["tokyo"]},
    "NZD_JPY": {"pip_size": 0.01, "pip_value_per_unit": 0.01, "min_units": 1, "avg_spread_pips": 2.5, "sessions": ["tokyo"]},

    # === EUR CROSSES — best during London session ===
    "EUR_GBP": {"pip_size": 0.0001, "pip_value_per_unit": 0.0001, "min_units": 1, "avg_spread_pips": 1.3, "sessions": ["london"]},
    "EUR_AUD": {"pip_size": 0.0001, "pip_value_per_unit": 0.0001, "min_units": 1, "avg_spread_pips": 2.0, "sessions": ["london"]},
    "EUR_CAD": {"pip_size": 0.0001, "pip_value_per_unit": 0.0001, "min_units": 1, "avg_spread_pips": 2.2, "sessions": ["london"]},
    "EUR_CHF": {"pip_size": 0.0001, "pip_value_per_unit": 0.0001, "min_units": 1, "avg_spread_pips": 1.8, "sessions": ["london"]},
    "EUR_NZD": {"pip_size": 0.0001, "pip_value_per_unit": 0.0001, "min_units": 1, "avg_spread_pips": 3.0, "sessions": ["london"]},

    # === GBP CROSSES — best during London session ===
    "GBP_AUD": {"pip_size": 0.0001, "pip_value_per_unit": 0.0001, "min_units": 1, "avg_spread_pips": 3.0, "sessions": ["london"]},
    "GBP_CAD": {"pip_size": 0.0001, "pip_value_per_unit": 0.0001, "min_units": 1, "avg_spread_pips": 3.5, "sessions": ["london"]},
    "GBP_CHF": {"pip_size": 0.0001, "pip_value_per_unit": 0.0001, "min_units": 1, "avg_spread_pips": 3.0, "sessions": ["london"]},
    "GBP_NZD": {"pip_size": 0.0001, "pip_value_per_unit": 0.0001, "min_units": 1, "avg_spread_pips": 4.0, "sessions": ["london"]},

    # === AUD/NZD CROSSES — best during Tokyo/Sydney overlap ===
    "AUD_NZD": {"pip_size": 0.0001, "pip_value_per_unit": 0.0001, "min_units": 1, "avg_spread_pips": 2.5, "sessions": ["tokyo"]},
    "AUD_CAD": {"pip_size": 0.0001, "pip_value_per_unit": 0.0001, "min_units": 1, "avg_spread_pips": 2.5, "sessions": ["tokyo"]},
    "AUD_CHF": {"pip_size": 0.0001, "pip_value_per_unit": 0.0001, "min_units": 1, "avg_spread_pips": 2.5, "sessions": ["tokyo"]},
    "NZD_CAD": {"pip_size": 0.0001, "pip_value_per_unit": 0.0001, "min_units": 1, "avg_spread_pips": 3.0, "sessions": ["tokyo"]},
    "NZD_CHF": {"pip_size": 0.0001, "pip_value_per_unit": 0.0001, "min_units": 1, "avg_spread_pips": 3.0, "sessions": ["tokyo"]},

    # === CAD/CHF CROSSES ===
    "CAD_CHF": {"pip_size": 0.0001, "pip_value_per_unit": 0.0001, "min_units": 1, "avg_spread_pips": 2.5, "sessions": ["newyork"]},
    "CHF_JPY": {"pip_size": 0.01, "pip_value_per_unit": 0.01, "min_units": 1, "avg_spread_pips": 2.0, "sessions": ["london"]},
}

# ALL global trading sessions (UTC)
# Forex is 24/5 — these overlap to create continuous coverage
TRADING_SESSIONS = {
    "sydney":    {"start": 21, "end": 6},   # 21:00 - 06:00 UTC (crosses midnight)
    "tokyo":     {"start": 0, "end": 9},    # 00:00 - 09:00 UTC
    "shanghai":  {"start": 1, "end": 9},    # 01:00 - 09:00 UTC (overlaps Tokyo)
    "singapore": {"start": 1, "end": 9},    # 01:00 - 09:00 UTC (overlaps Tokyo)
    "mumbai":    {"start": 3, "end": 12},   # 03:30 - 11:30 UTC (bridges Asia→Europe)
    "dubai":     {"start": 4, "end": 12},   # 04:00 - 12:00 UTC (bridges Asia→Europe)
    "frankfurt": {"start": 7, "end": 16},   # 07:00 - 16:00 UTC (opens with London)
    "london":    {"start": 7, "end": 16},   # 07:00 - 16:00 UTC (highest volume)
    "newyork":   {"start": 13, "end": 22},  # 13:00 - 22:00 UTC
    "chicago":   {"start": 14, "end": 22},  # 14:00 - 22:00 UTC (overlaps NY)
    "toronto":   {"start": 13, "end": 22},  # 13:00 - 22:00 UTC (overlaps NY)
}
# Key overlaps (highest liquidity windows):
#   Tokyo + Sydney:  21:00 - 06:00 UTC
#   Tokyo + London:  07:00 - 09:00 UTC  (Asia → Europe handoff)
#   London + NY:     13:00 - 16:00 UTC  (HIGHEST VOLUME WINDOW)
#   NY close:        20:00 - 22:00 UTC  (thinnest liquidity)

# Correlation matrix for risk management (approximate 2024-2026 values)
PAIR_CORRELATIONS = {
    # Strong positive correlations (>0.7) — treat as near-duplicate exposure
    ("EUR_USD", "GBP_USD"): 0.87,
    ("EUR_USD", "AUD_USD"): 0.75,
    ("EUR_USD", "NZD_USD"): 0.72,
    ("GBP_USD", "AUD_USD"): 0.70,
    ("AUD_USD", "NZD_USD"): 0.92,    # very high — almost same trade
    ("EUR_JPY", "GBP_JPY"): 0.85,
    ("EUR_GBP", "EUR_CHF"): 0.72,
    ("AUD_JPY", "NZD_JPY"): 0.88,

    # Strong negative correlations — effectively opposite trades
    ("EUR_USD", "USD_CHF"): -0.92,
    ("GBP_USD", "USD_CHF"): -0.80,
    ("AUD_USD", "USD_CAD"): -0.70,

    # Moderate correlations (0.5-0.7)
    ("USD_JPY", "USD_CAD"): 0.55,
    ("EUR_USD", "EUR_JPY"): 0.65,
    ("GBP_USD", "GBP_JPY"): 0.60,
}
